### ISSUE TITLE
Cannot change private variable _full_duplex

### ISSUE THREAD

**Issue by RXTX4816** [domnulvlad/KLineKWP1281Lib#10]
# **Background**
KLineKWP1281Lib.h 
KLineKWP1281Lib.cpp

# **Is**
Once an instance of the library is created the private variable _full_duplex cannot be changed

# **Notes**
Hey! I'm almost done with the refactor - finally got a working version on the ARDUINO_MEGA by using your library :)

While refactoring the User Interface I discovered there is no public setter for the _full_duplex that is used for UART echo.

**_Usecase:_** 
OBD Diagnostic device:
-> Starts ( initial creation of library instance ) 
-> Setup screen to choose baud_rate, ecu_addr, ... and whether to use full_duplex
-> Connect [...]
-> Disconnect -> Setup screen ( preserve library instance )

Is it possible to add this to the lib? See code below (Tested through UI). The alternative would be to recreate the instance when I enter the Setup screen if I see correctly - but since I'm not an expert in cpp specifics I don't know about the garbage collection etc.

Thanks! 

Possible solution:

### KLineKWP1281Lib.h
```cpp
[...]
// Setters
void setFullDuplex(bool is_full_duplex);

private:
///VARIABLES/TYPES
[...]
```

### KLineKWP1281Lib.cpp
```cpp
[...]
/**
  Function:
    setFullDuplex(bool is_full_duplex)

  Parameters:
    is_full_duplex -> whether to send an UART echo

  Returns:
    void -> N/A

  Description:
    Setter for variable _full_duplex

  Notes:
    *It is NOT a static function, so it DOES require an instance to be used.
*/
void KLineKWP1281Lib::setFullDuplex(bool is_full_duplex) {
  _full_duplex = is_full_duplex;
}
[...]
```

**Comment by domnulvlad** [comment]
Why would you need to change full_duplex at runtime?

Whether you set it to true or false depends on your chosen UART (if it can receive while sending) and possibly on your K-line interface (if it echoes sent bytes, but it should always do).

I assumed it would suffice to hardcode this parameter in your sketch, since it depends on your hardware, not on which module you want to diagnose or whatever.

**Comment by RXTX4816** [comment]
Oops I realized I misunderstood how the Hardwareserial works :D

Since the KWP1281 document J2818_200801 costs a whopping 100$ lets just assume it defines ECHO on sync bytes mandatory and also lets assume every ECU respects the protocol in that regard.

Thanks for clarifying! :) You can close the issue

**Comment by domnulvlad** [comment]
I've heard that document is pretty much useless.

In any case, the echo of every byte is not a property of KWP1281, but of the K-line interface. Having 2-way communication on 1 wire means you will always "see" what you are sending on it, because the wire is RX and TX at the same time.

If you don't have any HardwareSerial available and you choose a SoftwareSerial implementation that can't "pay attention" to RX while TX-ing, then you must tell my library not to expect echoes, because those bytes will never be received.
